---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-mqcloud
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 7ee5876d-6e30-49d1-be25-259a442085e8
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
